### ISSUE TITLE
의미 없는 코드

### ISSUE THREAD

**Issue by nattybear** [pottybear/CodingAnythings#6]
https://github.com/pottybear/CodingAnythings/blob/1b0de600705c168a418fe7ab0d5b23a7d289d786/SumIt.py#L8

이 코드의 의도는 뮌가요?

`int` 함수는 메소드가 아니라 글로벌 함수입니다. 따라서 이 코드는 전체 코드에 아무런 영향을 주지 않을 것 같습니다.

**Comment by pottybear** [comment]
먼저 저는 `변수 a`에 사용자의 입력을 담는 함수를 만들어봤습니다.

try-except 예외처리 문법을 이용해서, 만약 a에 오로지 숫자로 구성된 입력이 들어오지 않는 경우에는

`int(a)`는 오류가 발생될 것이고 그것을 트리거 삼아 다시 입력을 받도록 구성해봤습니다.

`int(a)`는 오류검사의 트리거 입니다.

**Comment by nattybear** [comment]
와 그런 의도가 있었군요... 놀라워요 ㅎ 역시 세상은 넓어요 ㅎ
